# Generated by Django 5.2.5 on 2025-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/images/')),
                ('qualification', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuedate', models.DateField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
